
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ifan
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etNama = new javax.swing.JTextField();
        etID = new javax.swing.JTextField();
        etStAwal = new javax.swing.JTextField();
        etStTujuan = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jKereta = new javax.swing.JComboBox<>();
        etWaktu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        BtnSave = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnPrint = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        etHarga = new javax.swing.JTextField();
        jDuduk = new javax.swing.JComboBox<>();
        BtnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMESANAN TIKET KERETA API");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 20, 420, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 810, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Isi Data Pemesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pemesan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 130, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NO ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 130, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Station Awal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 130, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Station Tujuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 290, 130, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Berangkat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 110, 130, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kereta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 160, 130, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Waktu Berangkat");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 210, 130, 30);
        getContentPane().add(etNama);
        etNama.setBounds(170, 140, 170, 30);
        getContentPane().add(etID);
        etID.setBounds(170, 190, 170, 30);

        etStAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etStAwalActionPerformed(evt);
            }
        });
        getContentPane().add(etStAwal);
        etStAwal.setBounds(170, 240, 170, 30);
        getContentPane().add(etStTujuan);
        etStTujuan.setBounds(170, 290, 170, 30);
        getContentPane().add(Tanggal);
        Tanggal.setBounds(550, 110, 170, 30);

        jKereta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jKereta);
        jKereta.setBounds(550, 160, 170, 30);
        getContentPane().add(etWaktu);
        etWaktu.setBounds(550, 210, 170, 30);

        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pemesan", "NO ID", "Station Awal", "Station Tujuan", "Tanggal Berangkat", "Jenis Kereta", "Waktu Berangkat", "Tempat Duduk", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tb1Data);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 430, 800, 150);

        BtnSave.setText("SAVE");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSave);
        BtnSave.setBounds(50, 380, 120, 30);

        BtnClear.setText("CLEAR");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear);
        BtnClear.setBounds(200, 380, 110, 30);

        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDelete);
        BtnDelete.setBounds(340, 380, 110, 30);

        BtnPrint.setText("PRINT");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrint);
        BtnPrint.setBounds(480, 380, 110, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tempat Duduk");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 270, 130, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Harga");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 320, 130, 30);
        getContentPane().add(etHarga);
        etHarga.setBounds(550, 320, 170, 30);

        jDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5", "Gerbong 6" }));
        getContentPane().add(jDuduk);
        jDuduk.setBounds(550, 270, 170, 30);

        BtnRefresh.setText("REFRESH");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRefresh);
        BtnRefresh.setBounds(620, 380, 110, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 800, 260);

        setBounds(0, 0, 812, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void etStAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etStAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etStAwalActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate()); 
        
        if (etNama.getText().equals("") || etID.getText().equals("") || etStAwal.getText().equals("") || etStTujuan.getText().equals("") ||
            tanggal.equals("") || jKereta.getSelectedItem().equals("") || etWaktu.getText().equals("") || jDuduk.getSelectedItem().equals("") || etHarga.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        String SQL = "INSERT INTO tb_data (NamaPemesan,NOID,StationAwal,StationTujuan,TanggalKeberangkatan,JenisKereta,WaktuBerangkat,TempatDuduk,Harga)"
                + "VALUES ('"+etNama.getText()+"','"+etID.getText()+"','"+etStAwal.getText()+"','"+etStTujuan.getText()+"','"+tanggal+"','"+jKereta.getSelectedItem()+"','"+etWaktu.getText()+"','"+jDuduk.getSelectedItem()+"','"+etHarga.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }else {
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        etNama.setText("");
        etID.setText("");
        etStAwal.setText("");
        etStTujuan.setText("");
        jKereta.setToolTipText("");
        etWaktu.setText("");
        jDuduk.setToolTipText("");
        etHarga.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tb1Data.getSelectedRow();
        if(baris != -1) {
            String NOID = tb1Data.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_data WHERE NOID='"+NOID+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("Pemesanan Tiket Kereta Api");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
        tb1Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_BtnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSave;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JTextField etHarga;
    private javax.swing.JTextField etID;
    private javax.swing.JTextField etNama;
    private javax.swing.JTextField etStAwal;
    private javax.swing.JTextField etStTujuan;
    private javax.swing.JTextField etWaktu;
    private javax.swing.JComboBox<String> jDuduk;
    private javax.swing.JComboBox<String> jKereta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1Data;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NamaPemesan","NOID","StationAwal","StationTujuan","TanggalKeberangkatan","JenisKereta","WaktuBerangkat","TempatDuduk","Harga"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM tb_data";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String NamaPemesan = rs.getString(1);
                        String NOID = rs.getString(2);
                        String StationAwal = rs.getString(3);
                        String StationTujuan = rs.getString(4);
                        String TanggalKeberangkatan = rs.getString(5);
                        String JenisKereta = rs.getString(6);
                        String WaktuBerangkat = rs.getString(7);
                        String TempatDuduk = rs.getString(8);
                        String Harga = rs.getString(9);
                        String data[] = {NamaPemesan,NOID,StationAwal,StationTujuan,TanggalKeberangkatan,JenisKereta,WaktuBerangkat,TempatDuduk,Harga};
                        dtm.addRow(data);
                    }
                }catch (SQLException ex){
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
                }
                tb1Data.setModel(dtm);
    }
}
